apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: openshift-gitops
spec:
  destination:
    namespace: front
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/Saravanan1705/test.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
