name: Jira Approval
on:
  push:
    branches-ignore:
      - main
jobs:
  job:
    name: Ticket Labels
    runs-on: ubuntu-latest
    steps:
      - name: Jira Ticket Labels
        uses: g2crowd/required-approvals-action@v1.6
        with:
          commit_message: ${{ github.event.commits[0]['message'] }}
          jira_user: saravanan.n@prodevans.com
          jira_token: ATATT3xFfGF0d1dFcWY4SE882QX9SvAmvEf8CpvnHx5PhXqJVOcyyIfOf2Maj18laD060NWhHPE1wrJMsU4YinQNKCrRjb45T3xJ4yg18bK5oR36xepYPjbmfVu_88PRYTcLWyHA74n3eVUlb9O1qf23vR59jYWZ2Q96CaOzf6A6U9hv8nCR6XU=7C02915B
          jira_url: https://prodevans-saravanann.atlassian.net
