name: Jira Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: |
          ./gradlew build

      - name: Create Jira Issue
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://prodevans-saravanann.atlassian.net'
        run: |
          curl -u $JIRA_USERNAME:$JIRA_API_TOKEN -X POST -H "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "KAN"
                },
                "summary": "YOUR_SUMMARY",
                "issuetype": {
                  "name": "Task"
                }
              }
            }' \
            $JIRA_BASE_URL/rest/api/2/issue/
