name: Jira Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: |
          ./gradlew build

      - name: Update Jira Issue
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          ISSUE_KEY=${{ steps.extract_issue_key.outputs.key }}
          curl -u $JIRA_USERNAME:$JIRA_API_TOKEN -X PUT -H "Content-Type: application/json" -d '{"fields":{"summary":"Updated Summary"}}' https://prodevans-saravanann.atlassian.net/rest/api/2/issue/$ISSUE_KEY

