name: Jira Integration

on:
  push:
    branches:
      - main

jobs:
  notify-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Notify Jira
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://prodevans-saravanann.atlassian.net'
        run: |
          curl -X POST -H "Authorization: Basic $(echo -n username:$JIRA_API_TOKEN | base64)" -H "Content-Type: application/json" -d '{"key": "MY Kanban Project", "transition": {"id": "2"}}' $JIRA_BASE_URL/rest/api/2/issue/KAN-3/transitions

        
